using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcall.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Xml.Linq;
using FluentAssertions;
using Xunit;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using SoapHttpClient.Enums;
using SoapHttpClient.DTO;

namespace SoapHttpClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private static readonly HttpClient httpClient = new HttpClient();


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async void Index()
        {

            string url = "http://sscweb.gsfc.nasa.gov:80/WS/helio/1/HeliocentricTrajectoriesService";
            string xmlSOAP = @"soapenv:Envelope xmlns:soapenv=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:tem=""http://tempuri.org/""
            xmlns: qxi = ""http://schemas.datacontract.org/2004/07/QXI.DataTransferObjects.QNXT.V500.S000.C000"" xmlns: qxi1 = ""
http://schemas.datacontract.org/2004/07/QXI.Messages.QNXT.V500.S000.C000.Claim"">
              <soapenv:Header>
                <tem:RequestContext>
                    <qxi:CallingApplication>?</qxi:CallingApplication>
                    <qxi:ConstituentId>?</qxi:ConstituentId>
                    <qxi:ConstituentType>?</qxi:ConstituentType>
                    <qxi:Environment>?</qxi:Environment>
                    <qxi:MessagingDestination>?</qxi:MessagingDestination>
                    <qxi:Password>?</qxi:Password>
                    <qxi:ProcessLogDetailId>?</qxi:ProcessLogDetailId>
                    <qxi:ProcessLogHeaderId>?</qxi:ProcessLogHeaderId>
                    <qxi:SystemId>?</qxi:SystemId>
                    <qxi:User>?</qxi:User>
                </tem:RequestContext>
                <tem:Partner>
                    <qxi:PartnerName>?</qxi:PartnerName>
                    <qxi:PartnerId>?</qxi:PartnerId>
                    <qxi:PartnerTime>?</qxi:PartnerTime>
                </tem:Partner>
              </soapenv:Header>
              <soapenv:Body>
                <tem:CreateClaimReqMsgWpr>
                    <!--Optional:-->
                    <tem:CreateClaimReqMsg>
                    <!--Optional:-->
                    <qxi1:Claim>
                    <!--Optional:-->
                    <qxi:HealthPlanId>?</qxi:HealthPlanId>
                    <!--Optional:-->
                    <qxi:PayToAffiliateId>?</qxi:PayToAffiliateId>
                    <qxi:ClaimType>?</qxi:ClaimType>
                    <qxi:FormType>?</qxi:FormType>
                    <qxi:ClaimMetaType>?</qxi:ClaimMetaType>
                    <qxi:StartDate>?</qxi:StartDate>
                    <!--Optional:-->
                    <qxi:EndDate>?</qxi:EndDate>
                    <!--Optional:-->
                    <qxi:MemberId>?</qxi:MemberId>
                    <qxi:ProviderId>?</qxi:ProviderId>
                    <!--Optional:-->
                    <qxi:PayToAffiliationId>?</qxi:PayToAffiliationId>
                    <!--Optional:-->
                    <qxi:ServiceAffiliateId>?</qxi:ServiceAffiliateId>
                    <!--Optional:-->
                    <qxi:ClaimIdPrefix>?</qxi:ClaimIdPrefix>
                    <!--Optional:-->
                    <qxi:ClaimIdUseCentury>?</qxi:ClaimIdUseCentury>
                    <!--Optional:-->
                    <qxi:AcceptAssignments>?</qxi:AcceptAssignments>
                    <!--Optional:-->
                    <qxi:AccidentState>?</qxi:AccidentState>
                    <!--Optional:-->
                    <qxi:AdmitDate>?</qxi:AdmitDate>
                    <!--Optional:-->
                    <qxi:AdmitHour>?</qxi:AdmitHour>
                    <!--Optional:-->
                    <qxi:AdmitSource>?</qxi:AdmitSource>
                    <!--Optional:-->
                    <qxi:AdmitType>?</qxi:AdmitType>
                    <!--Optional:-->
                    <qxi:BenefitsAssignment>?</qxi:BenefitsAssignment>
                    <!--Optional:-->
                    <qxi:BillType>?</qxi:BillType>
                    <!--Optional:-->
                    <qxi:CalcCobByLine>?</qxi:CalcCobByLine>
                    <!--Optional:-->
                    <qxi:ClaimSourceId>?</qxi:ClaimSourceId>
                    <!--Optional:-->
                    <qxi:CleanDate>?</qxi:CleanDate>
                    <!--Optional:-->
                    <qxi:CobPaidDate>?</qxi:CobPaidDate>
                    <!--Optional:-->
                    <qxi:ControlNumber>?</qxi:ControlNumber>
                    <!--Optional:-->
                    <qxi:DCN>?</qxi:DCN>
                    <!--Optional:-->
                    <qxi:DRG>?</qxi:DRG>
                    <!--Optional:-->
                    <qxi:DischargeDate>?</qxi:DischargeDate>
                    <!--Optional:-->
                    <qxi:DischargeHour>?</qxi:DischargeHour>
                    <!--Optional:-->
                    <qxi:EOBRequested>?</qxi:EOBRequested>
                    <!--Optional:-->
                    <qxi:Emergency>?</qxi:Emergency>
                    <!--Optional:-->
                    <qxi:EnrollmentId>?</qxi:EnrollmentId>
                    <!--Optional:-->
                    <qxi:EobAmount>?</qxi:EobAmount>
                    <!--Optional:-->
                    <qxi:EobEligibleAmount>?</qxi:EobEligibleAmount>
                    <!--Optional:-->
                    <qxi:Esc>?</qxi:Esc>
                    <!--Optional:-->
                    <qxi:EstAmtDue>?</qxi:EstAmtDue>
                    <!--Optional:-->
                    <qxi:ExpirationDate>?</qxi:ExpirationDate>
                    <!--Optional:-->
                    <qxi:ExternalEnrollId>?</qxi:ExternalEnrollId>
                    <!--Optional:-->
                    <qxi:ForcedBenePrefId>?</qxi:ForcedBenePrefId>
                    <!--Optional:-->
                    <qxi:FormCreationDate>?</qxi:FormCreationDate>
                    <!--Optional:-->
                    <qxi:HasDocuments>?</qxi:HasDocuments>
                    <!--Optional:-->
                    <qxi:HasLien>?</qxi:HasLien>
                    <!--Optional:-->
                    <qxi:InitialProthesis>?</qxi:InitialProthesis>
                    <!--Optional:-->
                    <qxi:IsAutoAccident>?</qxi:IsAutoAccident>
                    <!--Optional:-->
                    <qxi:IsEmployment>?</qxi:IsEmployment>
                    <!--Optional:-->
                    <qxi:IsEncounter>?</qxi:IsEncounter>
                    <!--Optional:-->
                    <qxi:IsItsClaim>?</qxi:IsItsClaim>
                    <!--Optional:-->
                    <qxi:IsLtc>?</qxi:IsLtc>
                    <!--Optional:-->
                    <qxi:IsOrthodontics>?</qxi:IsOrthodontics>
                    <!--Optional:-->
                    <qxi:IsOtherAccident>?</qxi:IsOtherAccident>
                    <!--Optional:-->
                    <qxi:IsRepricingClaim>?</qxi:IsRepricingClaim>
                    <!--Optional:-->
                    <qxi:IsReserved>?</qxi:IsReserved>
                    <!--Optional:-->
                    <qxi:IsStopLoss>?</qxi:IsStopLoss>
                    <!--Optional:-->
                    <qxi:LogDate>?</qxi:LogDate>
                    <!--Optional:-->
                    <qxi:MedRecNmb>?</qxi:MedRecNmb>
                    <!--Optional:-->
                    <qxi:MedicareCrossoverIndicator>?</qxi:MedicareCrossoverIndicator>
                    <!--Optional:-->
                    <qxi:MedicareCrossoverOccurred>?</qxi:MedicareCrossoverOccurred>
                    <!--Optional:-->
                    <qxi:MedicareRemittanceDate>?</qxi:MedicareRemittanceDate>
                    <!--Optional:-->
                    <qxi:MemPaidAmt>?</qxi:MemPaidAmt>
                    <!--Optional:-->
                    <qxi:MissingInformation>?</qxi:MissingInformation>
                    <!--Optional:-->
                    <qxi:MspClaim>?</qxi:MspClaim>
                    <!--Optional:-->
                    <qxi:NoWorkFromDate>?</qxi:NoWorkFromDate>
                    <!--Optional:-->
                    <qxi:NoWorkToDate>?</qxi:NoWorkToDate>
                    <!--Optional:-->
                    <qxi:NonCoveredDays>?</qxi:NonCoveredDays>
                    <!--Optional:-->
                    <qxi:OnsetDate>?</qxi:OnsetDate>
                    <!--Optional:-->
                    <qxi:OrthoApplDate>?</qxi:OrthoApplDate>
                    <!--Optional:-->
                    <qxi:OrthoMosRem>?</qxi:OrthoMosRem>
                    <qxi:EobAmount>?</qxi:EobAmount>
                    <!--Optional:-->
                    <qxi:EobEligibleAmount>?</qxi:EobEligibleAmount>
                    <!--Optional:-->
                    <qxi:Esc>?</qxi:Esc>
                    <!--Optional:-->
                    <qxi:EstAmtDue>?</qxi:EstAmtDue>
                    <!--Optional:-->
                    <qxi:ExpirationDate>?</qxi:ExpirationDate>
                    <!--Optional:-->
                    <qxi:ExternalEnrollId>?</qxi:ExternalEnrollId>
                    <!--Optional:-->
                    <qxi:ForcedBenePrefId>?</qxi:ForcedBenePrefId>
                    <!--Optional:-->
                    <qxi:FormCreationDate>?</qxi:FormCreationDate>
                    <!--Optional:-->
                    <qxi:HasDocuments>?</qxi:HasDocuments>
                    <!--Optional:-->
                    <qxi:HasLien>?</qxi:HasLien>
                    <!--Optional:-->
                    <qxi:InitialProthesis>?</qxi:InitialProthesis>
                    <!--Optional:-->
                    <qxi:IsAutoAccident>?</qxi:IsAutoAccident>
                    <!--Optional:-->
                    <qxi:IsEmployment>?</qxi:IsEmployment>
                    <!--Optional:-->
                    <qxi:IsEncounter>?</qxi:IsEncounter>
                    <!--Optional:-->
                    <qxi:IsItsClaim>?</qxi:IsItsClaim>
                    <!--Optional:-->
                    <qxi:IsLtc>?</qxi:IsLtc>
                    <!--Optional:-->
                    <qxi:IsOrthodontics>?</qxi:IsOrthodontics>
                    <!--Optional:-->
                    <qxi:IsOtherAccident>?</qxi:IsOtherAccident>
                    <!--Optional:-->
                    <qxi:IsRepricingClaim>?</qxi:IsRepricingClaim>
                    <!--Optional:-->
                    <qxi:IsReserved>?</qxi:IsReserved>
                    <!--Optional:-->
                    <qxi:IsStopLoss>?</qxi:IsStopLoss>
                    <!--Optional:-->
                    <qxi:LogDate>?</qxi:LogDate>
                    <!--Optional:-->
                    <qxi:MedRecNmb>?</qxi:MedRecNmb>
                    <!--Optional:-->
                    <qxi:MedicareCrossoverIndicator>?</qxi:MedicareCrossoverIndicator>
                    <!--Optional:-->
                    <qxi:MedicareCrossoverOccurred>?</qxi:MedicareCrossoverOccurred>
                    <!--Optional:-->
                    <qxi:MedicareRemittanceDate>?</qxi:MedicareRemittanceDate>
                    <!--Optional:-->
                    <qxi:MemPaidAmt>?</qxi:MemPaidAmt>
                    <!--Optional:-->
                    <qxi:MissingInformation>?</qxi:MissingInformation>
                    <!--Optional:-->
                    <qxi:MspClaim>?</qxi:MspClaim>
                    <!--Optional:-->
                    <qxi:NoWorkFromDate>?</qxi:NoWorkFromDate>
                    <!--Optional:-->
                    <qxi:NoWorkToDate>?</qxi:NoWorkToDate>
                    <!--Optional:-->
                    <qxi:NonCoveredDays>?</qxi:NonCoveredDays>
                    <!--Optional:-->
                    <qxi:OnsetDate>?</qxi:OnsetDate>
                    <!--Optional:-->
                    <qxi:OrthoApplDate>?</qxi:OrthoApplDate>
                    <!--Optional:-->
                    <qxi:OrthoMosRem>?</qxi:OrthoMosRem>
                    <!--Optional:-->
                    <qxi:Diag3>?</qxi:Diag3>
                    <!--Optional:-->
                    <qxi:Diag4>?</qxi:Diag4>
                    <!--Optional:-->
                    <qxi:Diag5>?</qxi:Diag5>
                    <!--Optional:-->
                    <qxi:Diag6>?</qxi:Diag6>
                    <!--Optional:-->
                    <qxi:Diag7>?</qxi:Diag7>
                    <!--Optional:-->
                    <qxi:Diag8>?</qxi:Diag8>
                    <!--Optional:-->
                    <qxi:Emergency>?</qxi:Emergency>
                    <!--Optional:-->
                    <qxi:Epsdt>?</qxi:Epsdt>
                    <!--Optional:-->
                    <qxi:ExtCoinsuranceAmt>?</qxi:ExtCoinsuranceAmt>
                    <!--Optional:-->
                    <qxi:ExtCopayAmt>?</qxi:ExtCopayAmt>
                    <!--Optional:-->
                    <qxi:ExtDeductAmt>?</qxi:ExtDeductAmt>
                    <!--Optional:-->
                    <qxi:IcdVersion>?</qxi:IcdVersion>
                    <!--Optional:-->
                    <qxi:IneligibleAmt>?</qxi:IneligibleAmt>
                    <!--Optional:-->
                    <qxi:LineProviderId>?</qxi:LineProviderId>
                    <!--Optional:-->
                    <qxi:Location>?</qxi:Location>
                    <!--Optional:-->
                    <qxi:MedicareActionCode>?</qxi:MedicareActionCode>
                    <!--Optional:-->
                    <qxi:ModCode>?</qxi:ModCode>
                    <!--Optional:-->
                    <qxi:ModCode2>?</qxi:ModCode2>
                    <!--Optional:-->
                    <qxi:Modcode3>?</qxi:Modcode3>
                    <!--Optional:-->
                    <qxi:Modcode4>?</qxi:Modcode4>
                    <!--Optional:-->
                    <qxi:Modcode5>?</qxi:Modcode5>
                    <!--Optional:-->
                    <qxi:PoolId>?</qxi:PoolId>
                    <!--Optional:-->
                    <qxi:PrinDiag>?</qxi:PrinDiag>
                    <!--Optional:-->
                    <qxi:ReferralId>?</qxi:ReferralId>
                    <!--Optional:-->
                    <qxi:RevCode>?</qxi:RevCode>
                    <!--Optional:-->
                    <qxi:ServCode>?</qxi:ServCode>
                    <!--Optional:-->
                    <qxi:ServUnits>?</qxi:ServUnits>
                    <!--Optional:-->
                    <qxi:ToothSurface>?</qxi:ToothSurface>
                    <!--Optional:-->
                    <qxi:Toothnumber>?</qxi:Toothnumber>
                    <!--Optional:-->
                    <qxi:PharmacyCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonPharmacyCode>
                    <!--Optional:-->
                    <qxi:MetricQty>?</qxi:MetricQty>
                    <qxi:NDCKey>?</qxi:NDCKey>
                    <!--Optional:-->
                    <qxi:DaysSupply>?</qxi:DaysSupply>
                    <qxi:IsPrimary>?</qxi:IsPrimary>
                    </qxi:CommonPharmacyCode>
                    </qxi:PharmacyCodes>
                    </qxi:CommonClaimDetail>
                    </qxi:Details>
                    <!--Optional:-->
                    <qxi:ConditionCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonConditionCode>
                    <qxi:ConditionCode>?</qxi:ConditionCode>
                    </qxi:CommonConditionCode>
                    </qxi:ConditionCodes>
                    <!--Optional:-->
                    <qxi:DiagnosisCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonDiagnosisCode>
                    <qxi:DiagnosisCode>?</qxi:DiagnosisCode>
                    <qxi:DiagnosisType>?</qxi:DiagnosisType>
                    <!--Optional:-->
                    <qxi:IsPrimary>?</qxi:IsPrimary>
                    <!--Optional:-->
                    <qxi:ICDVersion>?</qxi:ICDVersion>
                    <!--Optional:-->
                    <qxi:POA>?</qxi:POA>
                    </qxi:CommonDiagnosisCode>
                    </qxi:DiagnosisCodes>
                    <!--Optional:-->
                    <qxi:OccurenceCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonOccurrenceCode>
                    <qxi:OccurrenceCode>?</qxi:OccurrenceCode>
                    <!--Optional:-->
                    <qxi:OccurrenceType>?</qxi:OccurrenceType>
                    <qxi:StartDate>?</qxi:StartDate>
                    <!--Optional:-->
                    <qxi:EndDate>?</qxi:EndDate>
                    </qxi:CommonOccurrenceCode>
                    </qxi:OccurenceCodes>
                    <!--Optional:-->
                    <qxi:ProcedureCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonProcedureCode>
                    <qxi:ProcedureCode>?</qxi:ProcedureCode>
                    <qxi:IsPrimary>?</qxi:IsPrimary>
                    <qxi:ProcedureDate>?</qxi:ProcedureDate>
                    <!--Optional:-->
                    <qxi:ICDVersion>?</qxi:ICDVersion>
                    </qxi:CommonProcedureCode>
                    </qxi:ProcedureCodes>
                    <!--Optional:-->
                    <qxi:ValueCodes>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonValueCode>
                    <qxi:ValueCode>?</qxi:ValueCode>
                    <qxi:Amount>?</qxi:Amount>
                    </qxi:CommonValueCode>
                    </qxi:ValueCodes>
                    <!--Optional:-->
                    <qxi:ClaimProviders>
                    <!--Zero or more repetitions:-->
                    <qxi:CommonClaimProvider>
                    <!--Optional:-->
                    <qxi:ExternalProviderId>?</qxi:ExternalProviderId>
                    <!--Optional:-->
                    <qxi:ExternalProviderIdQualifier>?</qxi:ExternalProviderIdQualifier>
                    <!--Optional:-->
                    <qxi:FirstName>?</qxi:FirstName>
                    <!--Optional:-->
                    <qxi:LastName>?</qxi:LastName>
                    <!--Optional:-->
                    <qxi:NPI>?</qxi:NPI>
                    <!--Optional:-->
                    <qxi:ProviderId>?</qxi:ProviderId>
                    <qxi:ProviderType>?</qxi:ProviderType>
                    </qxi:CommonClaimProvider>
                    </qxi:ClaimProviders>
                    <!--Optional:-->
                    <qxi:OtherPayers>
                    <!--Zero or more repetitions:-->
                    <qxi:OtherPayerInfo>
                    <!--Optional:-->
                    <qxi:PayerSequence>?</qxi:PayerSequence>
                    <!--Optional:-->
                    <qxi:PaymentSource>?</qxi:PaymentSource>
                    <!--Optional:-->
                    <qxi:RelationId>?</qxi:RelationId>
                    <!--Optional:-->
                    <qxi:LastName>?</qxi:LastName>
                    <!--Optional:-->
                    <qxi:PayerName>?</qxi:PayerName>
                    <!--Optional:-->
                    <qxi:PayerId>?</qxi:PayerId>
                    <!--Optional:-->
                    <qxi:BenefitsAssignment>?</qxi:BenefitsAssignment>
                    <!--Optional:-->
                    <qxi:ReleaseOfInfo>?</qxi:ReleaseOfInfo>
                    <!--Optional:-->
                    <qxi:MedicareClaimNumber>?</qxi:MedicareClaimNumber>
                    <!--Optional:-->
                    <qxi:OtherCarrier>?</qxi:OtherCarrier>
                    <!--Optional:-->
                    <qxi:Details>
                    <!--Zero or more repetitions:-->
                    <qxi:OtherPayerDetail>
                    <qxi:ClaimLine>?</qxi:ClaimLine>
                    </qxi:OtherPayerDetail>
                    </qxi:Details>
                    <!--Optional:-->
                    <qxi:Addresses>
                    <!--Zero or more repetitions:-->
                    <qxi:OtherPayerAddress>
                    <!--Optional:-->
                    <qxi:AddressType>?</qxi:AddressType>
                    <!--Optional:-->
                    <qxi:Address1>?</qxi:Address1>
                    <!--Optional:-->
                    <qxi:Address2>?</qxi:Address2>
                    <!--Optional:-->
                    <qxi:City>?</qxi:City>
                    <!--Optional:-->
                    <qxi:State>?</qxi:State>
                    <!--Optional:-->
                    <qxi:Zip>?</qxi:Zip>
                    </qxi:OtherPayerAddress>
                    </qxi:Addresses>
                    <!--Optional:-->
                    <qxi:Adjustments>
                    <!--Zero or more repetitions:-->
                    <qxi:ClaimAdjustment>
                    <qxi:ClaimAdjustmentGroupCode>?</qxi:ClaimAdjustmentGroupCode>
                    <qxi:HipaaAdjReasonCodeId>?</qxi:HipaaAdjReasonCodeId>
                    <!--Optional:-->
                    <qxi:Amount>?</qxi:Amount>
                    </qxi:ClaimAdjustment>
                    </qxi:Adjustments>
                    <!--Optional:-->
                    <qxi:DetailAdjustments>
                    <!--Zero or more repetitions:-->
                    <qxi:ClaimDetailAdjustment>
                    <qxi:ClaimLine>?</qxi:ClaimLine>
                    <qxi:ClaimAdjustmentGroupCode>?</qxi:ClaimAdjustmentGroupCode>
                    <qxi:HipaaAdjReasonCodeId>?</qxi:HipaaAdjReasonCodeId>
                    <!--Optional:-->
                    <qxi:Amount>?</qxi:Amount>
                    </qxi:ClaimDetailAdjustment>
                    </qxi:DetailAdjustments>
                    </qxi:OtherPayerInfo>
                    </qxi:OtherPayers>
                    <!--Optional:-->
                    <qxi:ExternalMember>
                    <!--Optional:-->
                    <qxi:PatientId>?</qxi:PatientId>
                    <!--Optional:-->
                    <qxi:PatientLastName>?</qxi:PatientLastName>
                    <!--Optional:-->
                    <qxi:PatientFirstName>?</qxi:PatientFirstName>
                    <!--Optional:-->
                    <qxi:PatientMiddleInitial>?</qxi:PatientMiddleInitial>
                    <!--Optional:-->
                    <qxi:PatientAddress>?</qxi:PatientAddress>
                    <!--Optional:-->
                    <qxi:PatientAddress2>?</qxi:PatientAddress2>
                    <!--Optional:-->
                    <qxi:PatientCity>?</qxi:PatientCity>
                    <!--Optional:-->
                    <qxi:PatientState>?</qxi:PatientState>
                    <!--Optional:-->
                    <qxi:PatientZip>?</qxi:PatientZip>
                    <!--Optional:-->
                    <qxi:PatientPhone>?</qxi:PatientPhone>
                    <!--Optional:-->
                    <qxi:PatientDOB>?</qxi:PatientDOB>
                    <!--Optional:-->
                    <qxi:PatientGender>?</qxi:PatientGender>
                    <!--Optional:-->
                    <qxi:PatientRelationId>?</qxi:PatientRelationId>
                    <!--Optional:-->
                    <qxi:InsuredId>?</qxi:InsuredId>
                    <!--Optional:-->
                    <qxi:InsuredLastName>?</qxi:InsuredLastName>
                    <!--Optional:-->
                    <qxi:InsuredFirstName>?</qxi:InsuredFirstName>
                    <!--Optional:-->
                    <qxi:InsuredMiddleInitial>?</qxi:InsuredMiddleInitial>
                    <!--Optional:-->
                    <qxi:InsuredAddress>?</qxi:InsuredAddress>
                    <!--Optional:-->
                    <qxi:InsuredAddress2>?</qxi:InsuredAddress2>
                    <!--Optional:-->
                    <qxi:InsuredCity>?</qxi:InsuredCity>
                    <!--Optional:-->
                    <qxi:InsuredState>?</qxi:InsuredState>
                    <!--Optional:-->
                    <qxi:InsuredZip>?</qxi:InsuredZip>
                    <!--Optional:-->
                    <qxi:InsuredPhone>?</qxi:InsuredPhone>
                    <!--Optional:-->
                    <qxi:InsuredDOB>?</qxi:InsuredDOB>
                    <!--Optional:-->
                    <qxi:InsuredGender>?</qxi:InsuredGender>
                    <!--Optional:-->
                    <qxi:InsuredGroupnumber>?</qxi:InsuredGroupnumber>
                    </qxi:ExternalMember>
                    </qxi1:Claim>
                    </tem:CreateClaimReqMsg>
                  </tem:CreateClaimReqMsgWpr>
              </soapenv:Body>
       </soapenv:Envelope>";

            string soapcontent = @"soapenv:Envelope xmlns:soapenv=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:tem=""http://tempuri.org/""
            xmlns: qxi = ""http://schemas.datacontract.org/2004/07/QXI.DataTransferObjects.QNXT.V500.S000.C000"" xmlns: qxi1 = ""
http://schemas.datacontract.org/2004/07/QXI.Messages.QNXT.V500.S000.C000.Claim"">
          <soapenv:Header>
            <tem:RequestContext>";
                
            soapcontent += @"</tem:RequestContext>
            <tem:Partner>
                <qxi:PartnerName>?</qxi:PartnerName>
                <qxi:PartnerId>?</qxi:PartnerId>
                <qxi:PartnerTime>?</qxi:PartnerTime>
            </tem:Partner>
          </soapenv:Header>
          <soapenv:Body>
            <tem:CreateClaimReqMsgWpr>
                <!--Optional:-->
                <tem:CreateClaimReqMsg>
                <!--Optional:-->
                <qxi1:Claim>
                <!--Optional:-->
                <qxi:HealthPlanId>?</qxi:HealthPlanId>
                <!--Optional:-->
                <qxi:PayToAffiliateId>?</qxi:PayToAffiliateId>
                <qxi:ClaimType>?</qxi:ClaimType>
                <qxi:FormType>?</qxi:FormType>
                <qxi:ClaimMetaType>?</qxi:ClaimMetaType>
                <qxi:StartDate>?</qxi:StartDate>
                <!--Optional:-->
                <qxi:EndDate>?</qxi:EndDate>
                <!--Optional:-->
                <qxi:MemberId>?</qxi:MemberId>
                <qxi:ProviderId>?</qxi:ProviderId>
                <!--Optional:-->
                <qxi:PayToAffiliationId>?</qxi:PayToAffiliationId>
                <!--Optional:-->
                <qxi:ServiceAffiliateId>?</qxi:ServiceAffiliateId>
                <!--Optional:-->
                <qxi:ClaimIdPrefix>?</qxi:ClaimIdPrefix>
                <!--Optional:-->
                <qxi:ClaimIdUseCentury>?</qxi:ClaimIdUseCentury>
                <!--Optional:-->
                <qxi:AcceptAssignments>?</qxi:AcceptAssignments>
                <!--Optional:-->
                <qxi:AccidentState>?</qxi:AccidentState>
                <!--Optional:-->
                <qxi:AdmitDate>?</qxi:AdmitDate>
                <!--Optional:-->
                <qxi:AdmitHour>?</qxi:AdmitHour>
                <!--Optional:-->
                <qxi:AdmitSource>?</qxi:AdmitSource>
                <!--Optional:-->
                <qxi:AdmitType>?</qxi:AdmitType>
                <!--Optional:-->
                <qxi:BenefitsAssignment>?</qxi:BenefitsAssignment>
                <!--Optional:-->
                <qxi:BillType>?</qxi:BillType>
                <!--Optional:-->
                <qxi:CalcCobByLine>?</qxi:CalcCobByLine>
                <!--Optional:-->
                <qxi:ClaimSourceId>?</qxi:ClaimSourceId>
                <!--Optional:-->
                <qxi:CleanDate>?</qxi:CleanDate>
                <!--Optional:-->
                <qxi:CobPaidDate>?</qxi:CobPaidDate>
                <!--Optional:-->
                <qxi:ControlNumber>?</qxi:ControlNumber>
                <!--Optional:-->
                <qxi:DCN>?</qxi:DCN>
                <!--Optional:-->
                <qxi:DRG>?</qxi:DRG>
                <!--Optional:-->
                <qxi:DischargeDate>?</qxi:DischargeDate>
                <!--Optional:-->
                <qxi:DischargeHour>?</qxi:DischargeHour>
                <!--Optional:-->
                <qxi:EOBRequested>?</qxi:EOBRequested>
                <!--Optional:-->
                <qxi:Emergency>?</qxi:Emergency>
                <!--Optional:-->
                <qxi:EnrollmentId>?</qxi:EnrollmentId>
                <!--Optional:-->
                <qxi:EobAmount>?</qxi:EobAmount>
                <!--Optional:-->
                <qxi:EobEligibleAmount>?</qxi:EobEligibleAmount>
                <!--Optional:-->
                <qxi:Esc>?</qxi:Esc>
                <!--Optional:-->
                <qxi:EstAmtDue>?</qxi:EstAmtDue>
                <!--Optional:-->
                <qxi:ExpirationDate>?</qxi:ExpirationDate>
                <!--Optional:-->
                <qxi:ExternalEnrollId>?</qxi:ExternalEnrollId>
                <!--Optional:-->
                <qxi:ForcedBenePrefId>?</qxi:ForcedBenePrefId>
                <!--Optional:-->
                <qxi:FormCreationDate>?</qxi:FormCreationDate>
                <!--Optional:-->
                <qxi:HasDocuments>?</qxi:HasDocuments>
                <!--Optional:-->
                <qxi:HasLien>?</qxi:HasLien>
                <!--Optional:-->
                <qxi:InitialProthesis>?</qxi:InitialProthesis>
                <!--Optional:-->
                <qxi:IsAutoAccident>?</qxi:IsAutoAccident>
                <!--Optional:-->
                <qxi:IsEmployment>?</qxi:IsEmployment>
                <!--Optional:-->
                <qxi:IsEncounter>?</qxi:IsEncounter>
                <!--Optional:-->
                <qxi:IsItsClaim>?</qxi:IsItsClaim>
                <!--Optional:-->
                <qxi:IsLtc>?</qxi:IsLtc>
                <!--Optional:-->
                <qxi:IsOrthodontics>?</qxi:IsOrthodontics>
                <!--Optional:-->
                <qxi:IsOtherAccident>?</qxi:IsOtherAccident>
                <!--Optional:-->
                <qxi:IsRepricingClaim>?</qxi:IsRepricingClaim>
                <!--Optional:-->
                <qxi:IsReserved>?</qxi:IsReserved>
                <!--Optional:-->
                <qxi:IsStopLoss>?</qxi:IsStopLoss>
                <!--Optional:-->
                <qxi:LogDate>?</qxi:LogDate>
                <!--Optional:-->
                <qxi:MedRecNmb>?</qxi:MedRecNmb>
                <!--Optional:-->
                <qxi:MedicareCrossoverIndicator>?</qxi:MedicareCrossoverIndicator>
                <!--Optional:-->
                <qxi:MedicareCrossoverOccurred>?</qxi:MedicareCrossoverOccurred>
                <!--Optional:-->
                <qxi:MedicareRemittanceDate>?</qxi:MedicareRemittanceDate>
                <!--Optional:-->
                <qxi:MemPaidAmt>?</qxi:MemPaidAmt>
                <!--Optional:-->
                <qxi:MissingInformation>?</qxi:MissingInformation>
                <!--Optional:-->
                <qxi:MspClaim>?</qxi:MspClaim>
                <!--Optional:-->
                <qxi:NoWorkFromDate>?</qxi:NoWorkFromDate>
                <!--Optional:-->
                <qxi:NoWorkToDate>?</qxi:NoWorkToDate>
                <!--Optional:-->
                <qxi:NonCoveredDays>?</qxi:NonCoveredDays>
                <!--Optional:-->
                <qxi:OnsetDate>?</qxi:OnsetDate>
                <!--Optional:-->
                <qxi:OrthoApplDate>?</qxi:OrthoApplDate>
                <!--Optional:-->
                <qxi:OrthoMosRem>?</qxi:OrthoMosRem>
                <qxi:EobAmount>?</qxi:EobAmount>
                <!--Optional:-->
                <qxi:EobEligibleAmount>?</qxi:EobEligibleAmount>
                <!--Optional:-->
                <qxi:Esc>?</qxi:Esc>
                <!--Optional:-->
                <qxi:EstAmtDue>?</qxi:EstAmtDue>
                <!--Optional:-->
                <qxi:ExpirationDate>?</qxi:ExpirationDate>
                <!--Optional:-->
                <qxi:ExternalEnrollId>?</qxi:ExternalEnrollId>
                <!--Optional:-->
                <qxi:ForcedBenePrefId>?</qxi:ForcedBenePrefId>
                <!--Optional:-->
                <qxi:FormCreationDate>?</qxi:FormCreationDate>
                <!--Optional:-->
                <qxi:HasDocuments>?</qxi:HasDocuments>
                <!--Optional:-->
                <qxi:HasLien>?</qxi:HasLien>
                <!--Optional:-->
                <qxi:InitialProthesis>?</qxi:InitialProthesis>
                <!--Optional:-->
                <qxi:IsAutoAccident>?</qxi:IsAutoAccident>
                <!--Optional:-->
                <qxi:IsEmployment>?</qxi:IsEmployment>
                <!--Optional:-->
                <qxi:IsEncounter>?</qxi:IsEncounter>
                <!--Optional:-->
                <qxi:IsItsClaim>?</qxi:IsItsClaim>
                <!--Optional:-->
                <qxi:IsLtc>?</qxi:IsLtc>
                <!--Optional:-->
                <qxi:IsOrthodontics>?</qxi:IsOrthodontics>
                <!--Optional:-->
                <qxi:IsOtherAccident>?</qxi:IsOtherAccident>
                <!--Optional:-->
                <qxi:IsRepricingClaim>?</qxi:IsRepricingClaim>
                <!--Optional:-->
                <qxi:IsReserved>?</qxi:IsReserved>
                <!--Optional:-->
                <qxi:IsStopLoss>?</qxi:IsStopLoss>
                <!--Optional:-->
                <qxi:LogDate>?</qxi:LogDate>
                <!--Optional:-->
                <qxi:MedRecNmb>?</qxi:MedRecNmb>
                <!--Optional:-->
                <qxi:MedicareCrossoverIndicator>?</qxi:MedicareCrossoverIndicator>
                <!--Optional:-->
                <qxi:MedicareCrossoverOccurred>?</qxi:MedicareCrossoverOccurred>
                <!--Optional:-->
                <qxi:MedicareRemittanceDate>?</qxi:MedicareRemittanceDate>
                <!--Optional:-->
                <qxi:MemPaidAmt>?</qxi:MemPaidAmt>
                <!--Optional:-->
                <qxi:MissingInformation>?</qxi:MissingInformation>
                <!--Optional:-->
                <qxi:MspClaim>?</qxi:MspClaim>
                <!--Optional:-->
                <qxi:NoWorkFromDate>?</qxi:NoWorkFromDate>
                <!--Optional:-->
                <qxi:NoWorkToDate>?</qxi:NoWorkToDate>
                <!--Optional:-->
                <qxi:NonCoveredDays>?</qxi:NonCoveredDays>
                <!--Optional:-->
                <qxi:OnsetDate>?</qxi:OnsetDate>
                <!--Optional:-->
                <qxi:OrthoApplDate>?</qxi:OrthoApplDate>
                <!--Optional:-->
                <qxi:OrthoMosRem>?</qxi:OrthoMosRem>
                <!--Optional:-->
                <qxi:Diag3>?</qxi:Diag3>
                <!--Optional:-->
                <qxi:Diag4>?</qxi:Diag4>
                <!--Optional:-->
                <qxi:Diag5>?</qxi:Diag5>
                <!--Optional:-->
                <qxi:Diag6>?</qxi:Diag6>
                <!--Optional:-->
                <qxi:Diag7>?</qxi:Diag7>
                <!--Optional:-->
                <qxi:Diag8>?</qxi:Diag8>
                <!--Optional:-->
                <qxi:Emergency>?</qxi:Emergency>
                <!--Optional:-->
                <qxi:Epsdt>?</qxi:Epsdt>
                <!--Optional:-->
                <qxi:ExtCoinsuranceAmt>?</qxi:ExtCoinsuranceAmt>
                <!--Optional:-->
                <qxi:ExtCopayAmt>?</qxi:ExtCopayAmt>
                <!--Optional:-->
                <qxi:ExtDeductAmt>?</qxi:ExtDeductAmt>
                <!--Optional:-->
                <qxi:IcdVersion>?</qxi:IcdVersion>
                <!--Optional:-->
                <qxi:IneligibleAmt>?</qxi:IneligibleAmt>
                <!--Optional:-->
                <qxi:LineProviderId>?</qxi:LineProviderId>
                <!--Optional:-->
                <qxi:Location>?</qxi:Location>
                <!--Optional:-->
                <qxi:MedicareActionCode>?</qxi:MedicareActionCode>
                <!--Optional:-->
                <qxi:ModCode>?</qxi:ModCode>
                <!--Optional:-->
                <qxi:ModCode2>?</qxi:ModCode2>
                <!--Optional:-->
                <qxi:Modcode3>?</qxi:Modcode3>
                <!--Optional:-->
                <qxi:Modcode4>?</qxi:Modcode4>
                <!--Optional:-->
                <qxi:Modcode5>?</qxi:Modcode5>
                <!--Optional:-->
                <qxi:PoolId>?</qxi:PoolId>
                <!--Optional:-->
                <qxi:PrinDiag>?</qxi:PrinDiag>
                <!--Optional:-->
                <qxi:ReferralId>?</qxi:ReferralId>
                <!--Optional:-->
                <qxi:RevCode>?</qxi:RevCode>
                <!--Optional:-->
                <qxi:ServCode>?</qxi:ServCode>
                <!--Optional:-->
                <qxi:ServUnits>?</qxi:ServUnits>
                <!--Optional:-->
                <qxi:ToothSurface>?</qxi:ToothSurface>
                <!--Optional:-->
                <qxi:Toothnumber>?</qxi:Toothnumber>
                <!--Optional:-->
                <qxi:PharmacyCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonPharmacyCode>
                <!--Optional:-->
                <qxi:MetricQty>?</qxi:MetricQty>
                <qxi:NDCKey>?</qxi:NDCKey>
                <!--Optional:-->
                <qxi:DaysSupply>?</qxi:DaysSupply>
                <qxi:IsPrimary>?</qxi:IsPrimary>
                </qxi:CommonPharmacyCode>
                </qxi:PharmacyCodes>
                </qxi:CommonClaimDetail>
                </qxi:Details>
                <!--Optional:-->
                <qxi:ConditionCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonConditionCode>
                <qxi:ConditionCode>?</qxi:ConditionCode>
                </qxi:CommonConditionCode>
                </qxi:ConditionCodes>
                <!--Optional:-->
                <qxi:DiagnosisCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonDiagnosisCode>
                <qxi:DiagnosisCode>?</qxi:DiagnosisCode>
                <qxi:DiagnosisType>?</qxi:DiagnosisType>
                <!--Optional:-->
                <qxi:IsPrimary>?</qxi:IsPrimary>
                <!--Optional:-->
                <qxi:ICDVersion>?</qxi:ICDVersion>
                <!--Optional:-->
                <qxi:POA>?</qxi:POA>
                </qxi:CommonDiagnosisCode>
                </qxi:DiagnosisCodes>
                <!--Optional:-->
                <qxi:OccurenceCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonOccurrenceCode>
                <qxi:OccurrenceCode>?</qxi:OccurrenceCode>
                <!--Optional:-->
                <qxi:OccurrenceType>?</qxi:OccurrenceType>
                <qxi:StartDate>?</qxi:StartDate>
                <!--Optional:-->
                <qxi:EndDate>?</qxi:EndDate>
                </qxi:CommonOccurrenceCode>
                </qxi:OccurenceCodes>
                <!--Optional:-->
                <qxi:ProcedureCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonProcedureCode>
                <qxi:ProcedureCode>?</qxi:ProcedureCode>
                <qxi:IsPrimary>?</qxi:IsPrimary>
                <qxi:ProcedureDate>?</qxi:ProcedureDate>
                <!--Optional:-->
                <qxi:ICDVersion>?</qxi:ICDVersion>
                </qxi:CommonProcedureCode>
                </qxi:ProcedureCodes>
                <!--Optional:-->
                <qxi:ValueCodes>
                <!--Zero or more repetitions:-->
                <qxi:CommonValueCode>
                <qxi:ValueCode>?</qxi:ValueCode>
                <qxi:Amount>?</qxi:Amount>
                </qxi:CommonValueCode>
                </qxi:ValueCodes>
                <!--Optional:-->
                <qxi:ClaimProviders>
                <!--Zero or more repetitions:-->
                <qxi:CommonClaimProvider>
                <!--Optional:-->
                <qxi:ExternalProviderId>?</qxi:ExternalProviderId>
                <!--Optional:-->
                <qxi:ExternalProviderIdQualifier>?</qxi:ExternalProviderIdQualifier>
                <!--Optional:-->
                <qxi:FirstName>?</qxi:FirstName>
                <!--Optional:-->
                <qxi:LastName>?</qxi:LastName>
                <!--Optional:-->
                <qxi:NPI>?</qxi:NPI>
                <!--Optional:-->
                <qxi:ProviderId>?</qxi:ProviderId>
                <qxi:ProviderType>?</qxi:ProviderType>
                </qxi:CommonClaimProvider>
                </qxi:ClaimProviders>
                <!--Optional:-->
                <qxi:OtherPayers>
                <!--Zero or more repetitions:-->
                <qxi:OtherPayerInfo>
                <!--Optional:-->
                <qxi:PayerSequence>?</qxi:PayerSequence>
                <!--Optional:-->
                <qxi:PaymentSource>?</qxi:PaymentSource>
                <!--Optional:-->
                <qxi:RelationId>?</qxi:RelationId>
                <!--Optional:-->
                <qxi:LastName>?</qxi:LastName>
                <!--Optional:-->
                <qxi:PayerName>?</qxi:PayerName>
                <!--Optional:-->
                <qxi:PayerId>?</qxi:PayerId>
                <!--Optional:-->
                <qxi:BenefitsAssignment>?</qxi:BenefitsAssignment>
                <!--Optional:-->
                <qxi:ReleaseOfInfo>?</qxi:ReleaseOfInfo>
                <!--Optional:-->
                <qxi:MedicareClaimNumber>?</qxi:MedicareClaimNumber>
                <!--Optional:-->
                <qxi:OtherCarrier>?</qxi:OtherCarrier>
                <!--Optional:-->
                <qxi:Details>
                <!--Zero or more repetitions:-->
                <qxi:OtherPayerDetail>
                <qxi:ClaimLine>?</qxi:ClaimLine>
                </qxi:OtherPayerDetail>
                </qxi:Details>
                <!--Optional:-->
                <qxi:Addresses>
                <!--Zero or more repetitions:-->
                <qxi:OtherPayerAddress>
                <!--Optional:-->
                <qxi:AddressType>?</qxi:AddressType>
                <!--Optional:-->
                <qxi:Address1>?</qxi:Address1>
                <!--Optional:-->
                <qxi:Address2>?</qxi:Address2>
                <!--Optional:-->
                <qxi:City>?</qxi:City>
                <!--Optional:-->
                <qxi:State>?</qxi:State>
                <!--Optional:-->
                <qxi:Zip>?</qxi:Zip>
                </qxi:OtherPayerAddress>
                </qxi:Addresses>
                <!--Optional:-->
                <qxi:Adjustments>
                <!--Zero or more repetitions:-->
                <qxi:ClaimAdjustment>
                <qxi:ClaimAdjustmentGroupCode>?</qxi:ClaimAdjustmentGroupCode>
                <qxi:HipaaAdjReasonCodeId>?</qxi:HipaaAdjReasonCodeId>
                <!--Optional:-->
                <qxi:Amount>?</qxi:Amount>
                </qxi:ClaimAdjustment>
                </qxi:Adjustments>
                <!--Optional:-->
                <qxi:DetailAdjustments>
                <!--Zero or more repetitions:-->
                <qxi:ClaimDetailAdjustment>
                <qxi:ClaimLine>?</qxi:ClaimLine>
                <qxi:ClaimAdjustmentGroupCode>?</qxi:ClaimAdjustmentGroupCode>
                <qxi:HipaaAdjReasonCodeId>?</qxi:HipaaAdjReasonCodeId>
                <!--Optional:-->
                <qxi:Amount>?</qxi:Amount>
                </qxi:ClaimDetailAdjustment>
                </qxi:DetailAdjustments>
                </qxi:OtherPayerInfo>
                </qxi:OtherPayers>
                <!--Optional:-->
                <qxi:ExternalMember>
                <!--Optional:-->
                <qxi:PatientId>?</qxi:PatientId>
                <!--Optional:-->
                <qxi:PatientLastName>?</qxi:PatientLastName>
                <!--Optional:-->
                <qxi:PatientFirstName>?</qxi:PatientFirstName>
                <!--Optional:-->
                <qxi:PatientMiddleInitial>?</qxi:PatientMiddleInitial>
                <!--Optional:-->
                <qxi:PatientAddress>?</qxi:PatientAddress>
                <!--Optional:-->
                <qxi:PatientAddress2>?</qxi:PatientAddress2>
                <!--Optional:-->
                <qxi:PatientCity>?</qxi:PatientCity>
                <!--Optional:-->
                <qxi:PatientState>?</qxi:PatientState>
                <!--Optional:-->
                <qxi:PatientZip>?</qxi:PatientZip>
                <!--Optional:-->
                <qxi:PatientPhone>?</qxi:PatientPhone>
                <!--Optional:-->
                <qxi:PatientDOB>?</qxi:PatientDOB>
                <!--Optional:-->
                <qxi:PatientGender>?</qxi:PatientGender>
                <!--Optional:-->
                <qxi:PatientRelationId>?</qxi:PatientRelationId>
                <!--Optional:-->
                <qxi:InsuredId>?</qxi:InsuredId>
                <!--Optional:-->
                <qxi:InsuredLastName>?</qxi:InsuredLastName>
                <!--Optional:-->
                <qxi:InsuredFirstName>?</qxi:InsuredFirstName>
                <!--Optional:-->
                <qxi:InsuredMiddleInitial>?</qxi:InsuredMiddleInitial>
                <!--Optional:-->
                <qxi:InsuredAddress>?</qxi:InsuredAddress>
                <!--Optional:-->
                <qxi:InsuredAddress2>?</qxi:InsuredAddress2>
                <!--Optional:-->
                <qxi:InsuredCity>?</qxi:InsuredCity>
                <!--Optional:-->
                <qxi:InsuredState>?</qxi:InsuredState>
                <!--Optional:-->
                <qxi:InsuredZip>?</qxi:InsuredZip>
                <!--Optional:-->
                <qxi:InsuredPhone>?</qxi:InsuredPhone>
                <!--Optional:-->
                <qxi:InsuredDOB>?</qxi:InsuredDOB>
                <!--Optional:-->
                <qxi:InsuredGender>?</qxi:InsuredGender>
                <!--Optional:-->
                <qxi:InsuredGroupnumber>?</qxi:InsuredGroupnumber>
                </qxi:ExternalMember>
                </qxi1:Claim>
                </tem:CreateClaimReqMsg>
              </tem:CreateClaimReqMsgWpr>
          </soapenv:Body>
   </soapenv:Envelope>";

            /*var ns = XNamespace.Get("http://helio.spdf.gsfc.nasa.gov/");
            var body = new XElement(ns.GetName("getAllObjects"));

            var messageConfiguration = new SoapMessageConfiguration(SoapVersion.Soap11);
            var envelope = GetEnvelope(messageConfiguration);
            envelope.Add(new XElement(messageConfiguration.Schema + "Body", body));*/

            try
            {
                string result = await PostSOAPRequestAsync(url, xmlSOAP);
                System.Diagnostics.Debug.WriteLine(result);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }


        }

        private static async Task<string> PostSOAPRequestAsync(string url, string text)
        {
            using (HttpContent content = new StringContent(text, Encoding.UTF8, "text/xml"))
            using (HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, url))
            {
                request.Headers.Add("SOAPAction", "");
                request.Content = content;
                using (HttpResponseMessage response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead))
                {
                    //response.EnsureSuccessStatusCode(); // throws an Exception if 404, 500, etc.
                    return await response.Content.ReadAsStringAsync();
                }
            }
        }

        private static XElement GetEnvelope(SoapMessageConfiguration soapMessageConfiguration)
        {
            return new
                XElement(
                    soapMessageConfiguration.Schema + "Envelope",
                    new XAttribute(
                        XNamespace.Xmlns + "soapenv",
                        soapMessageConfiguration.Schema.NamespaceName));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}
